variables:
  HUGO_VERSION: "0.51"

production:
  image: python:latest
  script:
    - pip install awscli
    - wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
    - tar xvzf hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
    - mv ./hugo /usr/bin/hugo
    - hugo -s $CI_PROJECT_DIR
    - aws s3 cp $CI_PROJECT_DIR/public/ s3://$S3_BUCKET_NAME/ --recursive
  tags:
    - shared
  only:
    - master