production:
  image: python:latest
  type: deploy
  script:
    - pwd
    - pip install awscli
    - aws s3 cp $CI_PROJECT_DIR/s3_test/ s3://$S3_BUCKET_NAME/ --recursive
  tags:
    - shared
  # only:
  # - master
