production:
  image: python:latest
  type: deploy
  script:
    - pip install awscli
    - echo "deb http://deb.debian.org/debian stretch main" >> /etc/apt/sources.list
    - echo "deb http://deb.debian.org/debian stretch-updates main" >> /etc/apt/sources.list
    - apt update
    - apt install hugo
    - hugo -s $CI_PROJECT_DIR
    - aws s3 cp $CI_PROJECT_DIR/public/ s3://$S3_BUCKET_NAME/ --recursive
  tags:
    - shared
  only:
    - master