baseurl = "https://example.org/"
languageCode = "en-us"
title = "Steam - a minimal theme for Hugo"
theme = "unattended"
paginate = 10

[params]

	title = "Steam"
	# subtitle = "a minimal theme for ~~Ghost~~ Hugo"
	copyright = '<br>Unattended Theme under <a href="https://opensource.org/licenses/MIT">MIT license</a>.<br>Content under <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0 license</a>.'

	# You can choose between green, orange, red and blue.
	themeColor = "purple"


	# To provide some metadata for search engines and the about section in the footer
	# feel free to add a little information about you and your website.
	name = "Tyler Wengerd"
	bio = "The most terrifying move possible"
	description = "Your description of the blog"
	location = "" # optional
	twitter = "" # optional
	github = "" # optional
 	gitlab = "" # optional

	# Customize or translate the strings
	keepReadingStr = "Keep reading"
	backtotopStr = "Back to top"
	shareStr = "Share"
	pageNotFoundTitle = "404 - Page not found"
