baseurl = "https://hugo.tylerwengerd.com"
languageCode = "en-us"
title = "I've been left unattended: Tyler's blog"
theme = "unattended"
paginate = 7

[params]

	title = "I've been left unattended"
	# subtitle = "a minimal theme for ~~Ghost~~ Hugo"
	copyright = '<br>Unattended Theme under <a href="https://opensource.org/licenses/MIT">MIT license</a>.<br>Content under <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0 license</a>.'

	# You can choose between green, orange, red, blue, and purple.
	themeColor = "purple"


	# To provide some metadata for search engines and the about section in the footer
	# feel free to add a little information about you and your website.
	name = "Tyler Wengerd"
	bio = "You put that attitude away right now"
	description = "I write fiction about punctuation and other things."
	location = "" # optional
	twitter = "" # optional
	github = "" # optional
 	gitlab = "" # optional

	# Customize or translate the strings
	backtotopStr = "Back to top"
	shareStr = "Share this post"
	pageNotFoundTitle = "404 - Page not found"

	kickers = [
		"This is the secret one no one will see, are you going to spoil it for yourself and just read the rest? Up to you, cool either way, I'm too lazy to figure out how to obscure them",
		"I'm just saying, how do you pick, you know",
		"All words are written because they sound good, any meaning is purely coincidental",
		"This page also available digitally",
		"You will make winners of us all",
		'Thanks, Charles Joseph "Joe" Clark',
		"Remember the architects",
		"Stop it",
		"Deberá presentarse con su solicitud para el pasaporte debidamente llenada y con sus fotografías 15 minutos antes de su cita",
		"Beware of GHOOOOOOOOooooooOOOOO*cough*oooOOOooosts",
		"The the",
		"Now I have a big stapler and a little stapler",
		"Did you help propel Zoot Suit Riot to the top of Billboard's Top Heatseekers? Didn't think so",
		"We are -very- strict here",
		"It's...it's a little bit like SpiderMan, if that helps",
		"Squeak",
		"Squeak Squeak",
		"You brush against a leaf angrily",
		"There are exits to the north and west",
		"Oh god what time is it",
		"You have the voice of a harmonica player",
		"They're just carvings, don't worry about it",
		"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH",
		"I       Love       Rectangles",
		"You've seen one bungalow, you've seen 'em all",
		"What for? What store?",
		"Have you tried turning it off and on again then forgetting your favorite pen at home? That usually works for me",
		"This website is rad thanks to you and your haircut",
		"Judgment",
		"Burma Shave",
		"Oh Gus some day your super sniffer will be your undoing",
		"DISPOSE THE WORLD",
		"Everything will turn to dust, even that weird car on the street outside your window",
		"We are also a fully-featured daycare",
		"Flatbread? Who do you even think you're talking to",
		"Just another day",
		"So -- it's probably elephants",
		"My roadside assistance cost jumped up like three dollars, I'm like uh what well I guess that's fine, I've used it a couple times so it's still worth it I guess",
		"A jigsaw may be useful here",
		"PNRDD2D1",
		'All this time I thought it was "No trouble"',
		"Don't approve, never approve, that'll show 'em",
		"People in suits being pretty happy, I haven't forgotten about you",
		"A somber look at bushels",
		"You heard me"
	]
