baseurl = "https://example.org/"
languageCode = "en-us"
title = "I've been left unattended: Tyler's blog"
theme = "unattended"
paginate = 7

[params]

	title = "I've been left unattended"
	# subtitle = "a minimal theme for ~~Ghost~~ Hugo"
	copyright = '<br>Unattended Theme under <a href="https://opensource.org/licenses/MIT">MIT license</a>.<br>Content under <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0 license</a>.'

	# You can choose between green, orange, red, blue, and purple.
	themeColor = "purple"


	# To provide some metadata for search engines and the about section in the footer
	# feel free to add a little information about you and your website.
	name = "Tyler Wengerd"
	bio = "You put that attitude away right now"
	description = "Oh yikes"
	location = "" # optional
	twitter = "" # optional
	github = "" # optional
 	gitlab = "" # optional

	# Customize or translate the strings
	backtotopStr = "Back to top"
	shareStr = "Share this post"
	pageNotFoundTitle = "404 - Page not found"
